version: 2

sources:
  - name: raw
    database: student_engagement_analysis
    schema: raw
    tables:
      - name: course_info
      - name: course_ratings
      - name: exam_info
      - name: quiz_info
      - name: student_engagement
      - name: student_exams
      - name: student_info
      - name: student_learnings
      - name: student_purchases
      - name: student_questions
      - name: student_quizzes
